/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ml.socshared.adapter.fb;

import ml.socshared.adapter.fb.integration.AbstractIT;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;

import static org.junit.Assert.*;

public class ApplicationContextTest extends AbstractIT {

    @Autowired
    private Application application;

    @Test
    public void checkContextStarts() {
        assertNotNull(application);
    }

}
