/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ml.socshared.adapter.fb;

import ml.socshared.adapter.fb.integration.AbstractIT;
import org.junit.Test;

public class ApplicationContextTest extends AbstractIT {

    @Test
    public void checkContextStarts() {

    }

}
