image: java:11

stages:
  - build
  - docker-build
  - docker-push
  - docker-deploy-swarm

before_script:
  - chmod +x gradlew

build:
  stage: build
  script: ./gradlew clean build


docker-build:
  stage: docker-build
  script:
    - docker 2>/dev/null 1>&2 rmi `docker images -aq` || true
    - docker build -t $CI_DOCKER_LOGIN/socshared-adapter-fb .

docker-push:
  stage: docker-push
  script:
    - docker login -u "$CI_DOCKER_LOGIN" -p "$CI_DOCKER_PASSWORD"
    - docker push $CI_DOCKER_LOGIN/socshared-adapter-fb

docker-deploy-swarm:
  stage: docker-deploy-swarm
  script:
    - touch .env_fb
    - echo "SPRING_PROFILE=dev" >> .env_fb
    - echo "POSTGRES_HOST=postgres-db" >> .env_fb
    - echo "POSTGRES_USER=admin" >> .env_fb
    - echo "POSTGRES_PASSWORD=admin" >> .env_fb
    - echo "POSTGRES_DB=fb" >> .env_fb
    - echo "AUTH_SERVICE=auth-service:9999" >> .env_fb
    - docker stack deploy -c docker-compose.yaml socshared