version: '3.3'
services:
  socshared-adapter-fb:
    container_name: socshared-adapter-fb
    image: vee97/socshared-adapter-fb
    ports:
      - 8081:8081
    deploy:
      replicas: 1
    environment:
      SPRING_PROFILE: dev
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: 'facebook_db'

  postgres-db:
    image: postgres:11
    secrets:
      - postgres_password
    deploy:
      replicas: 1
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: 'facebook_db'

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin:2
    ports:
      - 9411:9411

secrets:
  postgres_password:
    external: true
