version: '3.7'
services:
  socshared-adapter-fb:
    image: vee97/socshared-adapter-fb
    ports:
      - 8081:8081
    deploy:
      replicas: 1
    environment:
      SPRING_PROFILE: dev
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_DB: 'facebook_db'

  postgres-db:
    image: postgres:11
    secrets:
      - postgres_password
    deploy:
      replicas: 1
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_DB: 'facebook_db'

  zipkin:
    image: openzipkin/zipkin:2
    ports:
      - 9411:9411

  keycloak:
    image: jboss/keycloak
    environment:
      KEYCLOAK_USER: socshared
      KEYCLOAK_PASSWORD: socshared
    ports:
      - 8080:8080

secrets:
  postgres_password:
    external: true
