version: '3.7'
services:
  socshared_adapter_fb:
    image: vee97/socshared-adapter-fb
    ports:
      - 8081:8081
    deploy:
      replicas: 1
    env_file:
      - .env_fb

networks:
  default:
    name: socshared
