spring:
  datasource:
    url: jdbc:h2:mem:facebook_db?useUnicode=yes&characterEncoding=UTF-8
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    hibernate:
      ddl-auto: update
  zipkin:
    enabled: false
  main:
    allow-bean-definition-overriding: true

keycloak:
  realm: dev
  auth-server-url: https://keycloak.socshared.ml/auth
  ssl-required: none
  resource: fb-socshared-adapter
  use-resource-role-mappings: false
  principal-attribute: preferred_username
  cors: true
  bearer-only: true

facebook:
  redirect:
    uri: http://localhost:8081/api/v1/token
  adapter:
    id: fb-adapter-local