spring:
  datasource:
    url: jdbc:postgresql://postgres-db:5432/facebook_db
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
  zipkin:
    base-url: http://zipkin:9411/
  main:
    allow-bean-definition-overriding: true

keycloak:
  realm: dev
  auth-server-url: https://keycloak.socshared.ml/auth
  ssl-required: none
  resource: fb-socshared-adapter
  use-resource-role-mappings: false
  principal-attribute: preferred_username
  cors: true
  bearer-only: true

facebook:
  redirect:
    uri: https://socshared.ml/connect/fb
  adapter:
    id: fb-adapter-dev