spring:
  datasource:
    url: jdbc:postgresql://postgres-db:5432/facebook_db
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

keycloak:
  enabled: false

facebook:
  redirect:
    uri: https://fb.socshared.ml/api/v1/token
  adapter:
    id: fb-adapter-prod