spring:
  datasource:
    url: jdbc:postgresql://postgres-db:5432/facebook_db
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  main:
    allow-bean-definition-overriding: true

facebook:
  redirect:
    uri: https://socshared.ml/connect/fb
  adapter:
    id: fb-adapter-prod