spring:
  datasource:
    url: jdbc:h2:mem:facebook_db?useUnicode=yes&characterEncoding=UTF-8
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    hibernate:
      ddl-auto: update
  zipkin:
    enabled: false
  main:
    allow-bean-definition-overriding: true

facebook:
  redirect:
    uri: http://localhost:8081/api/v1/token
  adapter:
    id: fb-adapter-local

feign:
  url:
    auth: ${AUTH_SERVICE:https://auth.socshared.ml}